# Generated by Django 4.2.6 on 2023-10-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiroute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hash', models.CharField(blank=True, editable=False, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ETL',
        ),
    ]
